<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="80990" started-at="2020-09-24T15:21:17 EEST" finished-at="2020-09-24T15:22:38 EEST">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="80990" started-at="2020-09-24T15:21:17 EEST" finished-at="2020-09-24T15:22:38 EEST">
      <class name="emp.attendence.AttendenceTest">
        <test-method status="PASS" signature="Start()[pri:0, instance:emp.attendence.AttendenceTest@185d8b6]" name="Start" is-config="true" duration-ms="27714" started-at="2020-09-24T15:21:17 EEST" finished-at="2020-09-24T15:21:45 EEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Start -->
        <test-method status="FAIL" signature="Attend()[pri:1, instance:emp.attendence.AttendenceTest@185d8b6]" name="Attend" duration-ms="16513" started-at="2020-09-24T15:21:45 EEST" finished-at="2020-09-24T15:22:01 EEST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<https://emp.roqay.com/panel/dashboard> but was:<https://emp.roqay.com/panel/front/attendance>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<https://emp.roqay.com/panel/dashboard> but was:<https://emp.roqay.com/panel/front/attendance>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:82)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:87)
at emp.attendence.AttendenceTest.Attend(AttendenceTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$49/222624801.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Attend -->
      </class> <!-- emp.attendence.AttendenceTest -->
      <class name="emp.attendence.LoginTest">
        <test-method status="PASS" signature="Start()[pri:0, instance:emp.attendence.LoginTest@67784306]" name="Start" is-config="true" duration-ms="21162" started-at="2020-09-24T15:22:01 EEST" finished-at="2020-09-24T15:22:22 EEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Start -->
        <test-method status="PASS" signature="login()[pri:0, instance:emp.attendence.LoginTest@67784306]" name="login" duration-ms="15515" started-at="2020-09-24T15:22:22 EEST" finished-at="2020-09-24T15:22:38 EEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- emp.attendence.LoginTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
